<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pid</name>
   <tag></tag>
   <elementGuidId>d4ced7d7-0b77-47a8-a0bb-7f8251ffc917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[@class='cellSelected'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isc_9Ttable&quot;]/tbody/tr/td[1]/div</value>
   </webElementProperties>
</WebElementEntity>
