<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>programstatusobj</name>
   <tag></tag>
   <elementGuidId>f4330b28-2a85-43a9-80c7-d017fe25fd45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;isc_PickListMenu_0_row_1&quot;]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isc_PickListMenu_0_row_1&quot;]/td/div</value>
   </webElementProperties>
</WebElementEntity>
