<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>programnameobj</name>
   <tag></tag>
   <elementGuidId>d42feeb2-8b65-46ed-a565-e1e7c747047e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;isc_PickListMenu_0_row_3&quot;]/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isc_PickListMenu_0_row_3&quot;]/td</value>
   </webElementProperties>
</WebElementEntity>
