<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gendermale</name>
   <tag></tag>
   <elementGuidId>9d06da98-d203-4181-9054-03ebdc35d1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>isc_PickListMenu_0_row_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@id='isc_PickListMenu_0_row_0']</value>
   </webElementProperties>
</WebElementEntity>
