<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchedpt</name>
   <tag></tag>
   <elementGuidId>cc2d9997-e501-4dd2-8416-d77fec076dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;isc_48&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isc_9Ttable&quot;]/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
