<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addbtn</name>
   <tag></tag>
   <elementGuidId>bc7ccc75-f5f8-4a66-9099-32f990bd36e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;patientEnrollmentTabBody_3&quot;]/div/md-content/gsi-program-table/ng-transclude/div/div[2]/div[2]/gsi-program-add-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;patientEnrollmentTabBody_3&quot;]/div/md-content/gsi-program-table/ng-transclude/div/div[2]/div[2]/gsi-program-add-button/button</value>
   </webElementProperties>
</WebElementEntity>
