<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cancelbtn</name>
   <tag></tag>
   <elementGuidId>093a343d-5d0f-4271-8586-913377a85acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;patientEnrollmentTabBody_1&quot;]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;patientEnrollmentTabBody_3&quot;]/div/div/button</value>
   </webElementProperties>
</WebElementEntity>
