<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deletebtn</name>
   <tag></tag>
   <elementGuidId>9aa04b1b-7e01-4de1-bed2-70f155361fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;popContainer&quot;]/div[16]/div/div/md-menu-item[2]</value>
   </webElementProperties>
</WebElementEntity>
