<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parentnameicon</name>
   <tag></tag>
   <elementGuidId>cfe60b8b-1d43-459b-83c4-e75ee89b34f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;patientEnrollmentTabBody_3&quot;]/div/md-content/gsi-program-table/ng-transclude/div/gsi-program-table-content/form/div[1]/div[2]/button/md-icon</value>
   </webElementProperties>
</WebElementEntity>
