<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>t1</name>
   <tag></tag>
   <elementGuidId>ff7e80d3-7d8f-4777-96c7-ab35fcc17222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;select_option_802&quot;]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//md-option[@id=&quot;select_option_803&quot;]</value>
   </webElementProperties>
</WebElementEntity>
